name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        timeout-minutes: 10
        run: DOCKER_BUILDKIT=1 docker build --target=build .
